from functools import wraps


def input_error(func):
    @wraps(func)
    def inner(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except ValueError:
            return "Invalid commandðŸ˜® Please provide the name and phone numberðŸ˜Š"
        except KeyError as e:
            return f"{e.args[0]}.ðŸ˜® Please provide the name of an existing contact.ðŸ˜Š"
        except IndexError:
            return "Invalid commandðŸ˜® Please provide a valid contact name.ðŸ˜Š"

    return inner